Workers with call_requests clean action
moonstream-to/api pull request #813
Opened 2023-06-08 14:18 UTC by kompotkot

Resolved Issuer https://github.com/moonstream-to/web3/issues/297

2023-06-12 16:39 UTC, zomglings requested changes
A few small comments. Let us deploy with `probes` as the name, and please consider my comment about unnesting the service definitions so that each JSON file represents a single service. Is there a use case for multiple services in the same file/process?

The architecture of this is very elegant, I like this new setup.

2023-06-12 16:39 UTC, zomglings commented on probs/README.md
> +# probs
`probs` -> `probes`

2023-06-12 16:39 UTC, zomglings commented on probs/cmd/probs/configs.go
> +					if worker.Name == engineWorker.Name {
Not really an issue, but it would be a good idea to define a `map[string]Worker` in engine instead of iterating like this.

2023-06-12 16:39 UTC, zomglings commented on probs/README.md
> +```json
Maybe better if this is not an array of services but rather a single service.

It is more consistent with the `probs service` command, and also less nesting in configuration is better.

2023-06-14 08:48 UTC, Andrei-Dolgolev approved these changes
Looks correct

2023-07-05 12:16 UTC, merged